jobs:
- name: job-upload-releases
  plan:
  - config:
      image_resource:
        source:
          repository: starkandwayne/concourse
        type: docker-image
      platform: linux
      run:
        args:
        - Eventually I will upload a bosh release
        path: echo
    task: upload-release
  public: true

